/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/BigBen.glb -o src/components/locations/BigBen1.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/BigBen.glb [594.5KB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\BigBen-transformed.glb [586.75KB] (1%)
*/

import { useGLTF } from '@react-three/drei'

export function BigBen(props) {
  const { nodes, materials } = useGLTF('/models/BigBen.glb')
  return (
    <group rotation={[0, Math.PI /4, 0]} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Big_Ben_big_ben_0" castShadow receiveShadow geometry={nodes.Big_Ben_big_ben_0.geometry} material={materials.big_ben} position={[1.966, 33, 1.966]} rotation={[-Math.PI / 2, 0, 0]} scale={0.17} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/BigBen.glb')
