/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Bisa.gltf -o src/components/locations/Bisa.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Bisa.gltf [3.36MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Bisa-transformed.glb [831.81KB] (75%)
*/

import { useGLTF } from '@react-three/drei'

export function Bisa(props) {
  const { nodes, materials } = useGLTF('/models/Bisa.glb')
  return (
    <group scale={3}{...props} dispose={null}>
      <group name="Scene">
        <mesh name="Bisa_Bisa_0" castShadow receiveShadow geometry={nodes.Bisa_Bisa_0.geometry} material={materials.Bisa} position={[0, 5.257, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Bisa.glb')
