/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Burj_KhalifaGLTF.gltf -o src/BurjKhalifa.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Burj_KhalifaGLTF.gltf [10.39KB] > C:\Users\Tomas\Desktop\3Dweather\src\Burj_KhalifaGLTF-transformed.glb [114.75KB] (-1004%)
*/

import { useGLTF } from '@react-three/drei'

export function BurjKhalifa(props) {
  const { nodes, materials } = useGLTF('/models/Burj_Khalifa.glb')
  return (
    <group scale={3} rotation={[0, - Math.PI / 4 , 0]} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="boli01_burj_khalifa_bubai_tower_0" castShadow receiveShadow geometry={nodes.boli01_burj_khalifa_bubai_tower_0.geometry} material={materials.burj_khalifa_bubai_tower} position={[-0.074, 10.278, 0.383]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02} />
        <mesh name="lou_ban_burj_khalifa_bubai_tower_1_0" castShadow receiveShadow geometry={nodes.lou_ban_burj_khalifa_bubai_tower_1_0.geometry} material={materials.burj_khalifa_bubai_tower_1} position={[-0.008, 10.418, 0.336]} rotation={[-Math.PI / 2, 0, 0.045]} scale={0.035} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Burj_Khalifa.glb')
