/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/CN_Tower.gltf -o src/components/locations/CN_Tower.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/CN_Tower.gltf [1.75MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\CN_Tower-transformed.glb [119.72KB] (93%)
*/

import { useGLTF } from '@react-three/drei'

export function CNTower(props) {
  const { nodes, materials } = useGLTF('/models/CN_Tower.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="di_ban_ground_cn_tower_0" castShadow receiveShadow geometry={nodes.di_ban_ground_cn_tower_0.geometry} material={materials.ground_cn_tower} rotation={[-Math.PI / 2, 0, -2.26]} scale={0.03} />
        <mesh name="dian_shi_tai_cn_tower_0" castShadow receiveShadow geometry={nodes.dian_shi_tai_cn_tower_0.geometry} material={materials.cn_tower} position={[0, 0.042, 0]} rotation={[-Math.PI / 2, 0, -2.26]} scale={0.03} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/CN_Tower.glb')
