/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Colosseum.gltf -o src/components/locations/Colosseum.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Colosseum.gltf [1.42MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Colosseum-transformed.glb [357.08KB] (75%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Colosseum(props) {
  const { nodes, materials } = useGLTF('/models/Colosseum.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Colosseum_Colosseum_0" castShadow receiveShadow geometry={nodes.Colosseum_Colosseum_0.geometry} material={materials.Colosseum} rotation={[0, 0.431, 0]} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Colosseum.glb')
