/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Eiffel512.glb -o src/Eiffel512.jsx -k -K -r public 
*/

import { useGLTF } from '@react-three/drei'

export function EifelTower(props) {
  const { nodes, materials } = useGLTF('/models/Eiffel_Tower.glb')
  const model = useGLTF('/models/Eiffel_Tower.glb')
 

  model.scene.traverse((object) => {
    if(object.isMesh){
      object.castShadow = true
    }
  })

  return (
    <group scale={4} {...props} dispose={null}>
      <group name="Scene">
      <primitive object={model.scene}/>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="b64dbcc2ba974b758d6d76dd2e2bb8adfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="buildings">
                <group name="Eiffel_Tower" position={[0, 549, -163]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="_15_Mini_Eiffel_Tower001" position={[198, 49, -22]}>
                    <mesh name="_15_Mini_Eiffel_Tower001_Eiffel_Tower_0" geometry={nodes._15_Mini_Eiffel_Tower001_Eiffel_Tower_0.geometry} material={materials.Eiffel_Tower} position={[-198, -212, 8.267]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Eiffel_Tower.glb')
