/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/London_Tower.gltf -o src/components/locations/LondonTower.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/London_Tower.gltf [5.03MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\London_Tower-transformed.glb [1.31MB] (74%)
*/

import { useGLTF } from '@react-three/drei'

export function LondonTower(props) {
  const { nodes, materials } = useGLTF('/models/London_Tower.glb')
  return (
    <group scale={4} rotation={[0, -Math.PI /3 , 0]} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="pCube175_London_Tower_Bridge_0" castShadow receiveShadow geometry={nodes.pCube175_London_Tower_Bridge_0.geometry} material={materials.London_Tower_Bridge} position={[0, 0.598, 0]} rotation={[Math.PI, 1.461, -Math.PI]} scale={[0.047, 0.006, 0.249]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/London_Tower.glb')
