/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Mesoamerican_Pyramid.gltf -o src/components/locations/MesoamericanPyramid.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Mesoamerican_Pyramid.gltf [1.3MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Mesoamerican_Pyramid-transformed.glb [181.02KB] (86%)
*/

import { useGLTF } from '@react-three/drei'

export function MesoamericanPyramid(props) {
  const { nodes, materials } = useGLTF('/models/Mesoamerican_Pyramid.glb')
  return (
    <group scale={4}{...props} rotation={[0, - Math.PI / 9, 0]} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Mesoamerican_pyramid_Mesoamerican_pyramid_0" castShadow receiveShadow geometry={nodes.Mesoamerican_pyramid_Mesoamerican_pyramid_0.geometry} material={materials.Mesoamerican_pyramid} rotation={[-Math.PI / 2, 0, 0]} scale={0.012} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Mesoamerican_Pyramid.glb')
