/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Notre_Dame_de_Paris.gltf -o src/components/locations/NotreDameDeParis.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Notre_Dame_de_Paris.gltf [6.15MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Notre_Dame_de_Paris-transformed.glb [632.63KB] (90%)
*/

import { useGLTF } from '@react-three/drei'

export function NotreDameDeParis(props) {
  const { nodes, materials } = useGLTF('/models/Notre_Dame_de_Paris.glb')
  return (
    <group rotation={[0, 0.5, 0]} scale={2}{...props} dispose={null}>
      <group name="Scene">
        <mesh name="er_lou_Notre_Dame_de_Paris_2_0" castShadow receiveShadow geometry={nodes.er_lou_Notre_Dame_de_Paris_2_0.geometry} material={materials.Notre_Dame_de_Paris_2} position={[0.661, 2.298, 0.001]} rotation={[0, -Math.PI / 2, 0]} scale={0.007} />
        <mesh name="yi_lou_Notre_Dame_de_Paris_3_0" castShadow receiveShadow geometry={nodes.yi_lou_Notre_Dame_de_Paris_3_0.geometry} material={materials.Notre_Dame_de_Paris_3} position={[2.641, 0.95, -0.002]} rotation={[0, -Math.PI / 2, 0]} scale={0.007} />
        <mesh name="zhu_lou_Notre_Dame_de_Paris_1_0" castShadow receiveShadow geometry={nodes.zhu_lou_Notre_Dame_de_Paris_1_0.geometry} material={materials.Notre_Dame_de_Paris_1} position={[-2.03, 2.042, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.007} />
        <mesh name="������001_1_Notre_Dame_de_Paris_4_0" castShadow receiveShadow geometry={nodes['������001_1_Notre_Dame_de_Paris_4_0'].geometry} material={materials.Notre_Dame_de_Paris_4} position={[-2.03, 2.042, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.007} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Notre_Dame_de_Paris.glb')
