/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/One_World_Trade_Center.gltf -o src/components/locations/OneWorldTradeCenter.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/One_World_Trade_Center.gltf [1.29MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\One_World_Trade_Center-transformed.glb [79.64KB] (94%)
*/

import { useGLTF } from '@react-three/drei'

export function OneWorldTradeCenter(props) {
  const { nodes, materials } = useGLTF('/models/One_World_Trade_Center.glb')
  return (
    <group scale={3}{...props} rotation={[0, - Math.PI, 0]} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="bo_li_glass_0_0" castShadow receiveShadow geometry={nodes.bo_li_glass_0_0.geometry} material={materials.glass_0} position={[0.009, -0.01, -0.008]} rotation={[-Math.PI / 2, 0, -1.311]} scale={1} />
        <mesh name="shi_mao_zhong_xin_One_World_Trade_Center_0" castShadow receiveShadow geometry={nodes.shi_mao_zhong_xin_One_World_Trade_Center_0.geometry} material={materials.One_World_Trade_Center} position={[0.009, -0.01, -0.008]} rotation={[-Math.PI / 2, 0, -1.311]} scale={1} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/One_World_Trade_Center.glb')
