/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Pyramid.gltf -o src/components/locations/Pyramid.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Pyramid.gltf [1.52MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Pyramid-transformed.glb [135.44KB] (91%)
*/

import { useGLTF } from '@react-three/drei'

export function Pyramid(props) {
  const { nodes, materials } = useGLTF('/models/Pyramid.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="men_dimo__1_pyramid_0" castShadow receiveShadow geometry={nodes.men_dimo__1_pyramid_0.geometry} material={materials['1_pyramid']} position={[0, 0.508, -2.978]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.02} />
        <mesh name="ta_dimo__2_pyramid_0" castShadow receiveShadow geometry={nodes.ta_dimo__2_pyramid_0.geometry} material={materials['2_pyramid']} position={[-0.07, 2.034, 0.07]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.02} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Pyramid.glb')
