/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Stonehenge.gltf -o src/components/locations/Stonehenge.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Stonehenge.gltf [4.87MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Stonehenge-transformed.glb [489.01KB] (90%)
*/

import { useGLTF } from '@react-three/drei'

export function Stonehenge(props) {
  const { nodes, materials } = useGLTF('/models/Stonehenge.glb')
  return (
    <group scale={3}{...props} dispose={null}>
      <group name="Scene">
        <mesh name="dimian_grass_0" castShadow receiveShadow geometry={nodes.dimian_grass_0.geometry} material={materials.grass} position={[0.033, 0, 0.055]} rotation={[-Math.PI / 2, 0, 0.188]} scale={0.007} />
        <mesh name="ju_shi_zhen_01_stonehenge_2_0" castShadow receiveShadow geometry={nodes.ju_shi_zhen_01_stonehenge_2_0.geometry} material={materials.stonehenge_2} rotation={[-Math.PI / 2, 0, 0.188]} scale={0.007} />
        <mesh name="ju_shi_zhen_02_stonehenge_1_0" castShadow receiveShadow geometry={nodes.ju_shi_zhen_02_stonehenge_1_0.geometry} material={materials.stonehenge_1} position={[0, -0.057, 0]} rotation={[-Math.PI / 2, 0, 0.188]} scale={0.007} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Stonehenge.glb')
