/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Sydney_Opera_House.gltf -o src/components/locations/SydneyOperaHouse.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Sydney_Opera_House.gltf [1.43MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Sydney_Opera_House-transformed.glb [127.2KB] (91%)
*/

import { useGLTF } from '@react-three/drei'

export function SydneyOperaHouse(props) {
  const { nodes, materials } = useGLTF('/models/Sydney_Opera_House.glb')
  return (
    <group scale={3}{...props} dispose={null}>
      <group name="Scene">
        <mesh name="_002__4_Sydney_Opera_House_0" castShadow receiveShadow geometry={nodes._002__4_Sydney_Opera_House_0.geometry} material={materials['4_Sydney_Opera_House']} position={[1.803, 1.291, 1.543]} rotation={[-Math.PI / 2, 0, 1.451]} scale={0.008} />
        <mesh name="_015__1_Sydney_Opera_House_0" castShadow receiveShadow geometry={nodes._015__1_Sydney_Opera_House_0.geometry} material={materials['1_Sydney_Opera_House']} position={[-0.236, 1.028, -0.11]} rotation={[-Math.PI / 2, 0, 1.78]} scale={[0.008, 0.009, 0.008]} />
        <mesh name="_016__3_Sydney_Opera_House_0" castShadow receiveShadow geometry={nodes._016__3_Sydney_Opera_House_0.geometry} material={materials['3_Sydney_Opera_House']} position={[-0.002, -0.071, 0.018]} rotation={[-Math.PI / 2, 0, 1.78]} scale={[0.008, 0.009, 0.008]} />
        <mesh name="archexteriors06_05_06__2_Sydney_Opera_House_0" castShadow receiveShadow geometry={nodes.archexteriors06_05_06__2_Sydney_Opera_House_0.geometry} material={materials['2_Sydney_Opera_House']} position={[1.522, 0.445, 0.824]} rotation={[-Math.PI / 2, 0, 1.924]} scale={[0.008, 0.007, 0.008]} />
        <mesh name="������001__5_Sydney_Opera_House_0" castShadow receiveShadow geometry={nodes['������001__5_Sydney_Opera_House_0'].geometry} material={materials['5_Sydney_Opera_House']} position={[1.522, 0.445, 0.824]} rotation={[-Math.PI / 2, 0, 1.924]} scale={[0.008, 0.007, 0.008]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Sydney_Opera_House.glb')
