/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Taj_Mahal.gltf -o src/components/locations/TajMahal.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Taj_Mahal.gltf [2.85MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Taj_Mahal-transformed.glb [708.46KB] (75%)
*/

import { useGLTF } from '@react-three/drei'

export function TajMahal(props) {
  const { nodes, materials } = useGLTF('/models/Taj_Mahal.glb')
  return (
    <group scale={2}{...props} dispose={null}>
      <group name="Scene">
        <mesh name="Taj_Mahal_glass_4_0" castShadow receiveShadow geometry={nodes.Taj_Mahal_glass_4_0.geometry} material={materials.glass_4} position={[0, 1.641, 0]} scale={0.01} />
        <mesh name="Taj_Mahal_Taj_Mahal_0" castShadow receiveShadow geometry={nodes.Taj_Mahal_Taj_Mahal_0.geometry} material={materials.Taj_Mahal} position={[0, 1.641, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Taj_Mahal.glb')
