/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Tokyo_Tower.gltf -o src/components/locations/TokyoTower.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Tokyo_Tower.gltf [2.45MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Tokyo_Tower-transformed.glb [578.07KB] (76%)
*/

import { useGLTF } from '@react-three/drei'

export function TokyoTower(props) {
  const { nodes, materials } = useGLTF('/models/Tokyo_Tower.glb')
  return (
    <group scale={4} rotation={[0,  - Math.PI / 3, 0]} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Tokyo_Tower_Tokyo_Tower_0" castShadow receiveShadow geometry={nodes.Tokyo_Tower_Tokyo_Tower_0.geometry} material={materials.Tokyo_Tower} position={[0, 4.003, 0]} rotation={[-Math.PI / 2, 0, 1.562]} scale={[0.045, 0.044, 0.044]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Tokyo_Tower.glb')
