/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Washington_Monument.gltf -o src/components/locations/WashingtonMonument.jsx -k -K -r -T -R 512 --draco -s public 
Files: public/models/Washington_Monument.gltf [1.1MB] > C:\Users\Tomas\Desktop\3Dweather\src\components\locations\Washington_Monument-transformed.glb [175.76KB] (84%)
*/

import { useGLTF } from '@react-three/drei'

export function WashingtonMonument(props) {
  const { nodes, materials } = useGLTF('/models/Washington_Monument.glb')
  return (
    <group sacale={3} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cylinder063_fence_0" castShadow receiveShadow geometry={nodes.Cylinder063_fence_0.geometry} material={materials.fence} scale={0.01} />
        <mesh name="Cylinder063_glass_5_0" castShadow receiveShadow geometry={nodes.Cylinder063_glass_5_0.geometry} material={materials.glass_5} scale={0.01} />
        <mesh name="Cylinder063_Washington_Monument_0" castShadow receiveShadow geometry={nodes.Cylinder063_Washington_Monument_0.geometry} material={materials.Washington_Monument} scale={0.01} />
        <mesh name="������001_2_flag_0" castShadow receiveShadow geometry={nodes['������001_2_flag_0'].geometry} material={materials.flag} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Washington_Monument.glb')
