/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Arc_de_Triomphe.glb -o src/ArcDeTriomphe.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ArcDeTriomphe(props) {
  const { nodes, materials } = useGLTF('/models/Arc_de_Triomphe.glb')
  return (
    <group scale={3} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="b64dbcc2ba974b758d6d76dd2e2bb8adfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="buildings">
                <group name="Arc_de_Triomphe" position={[-1310, 337, 1502]} rotation={[-Math.PI / 2, 0, 0]} scale={0.8}>
                  <mesh name="Arc_de_Triomphe_arc_de_triomphe_0" geometry={nodes.Arc_de_Triomphe_arc_de_triomphe_0.geometry} material={materials.arc_de_triomphe} position={[1637.5, 1725.206, 0.173]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Arc_de_Triomphe.glb')
