/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/direction_arrow.glb -o src/DirectionArrow.jsx -k -K -r public 
Author: Alihan (https://sketchfab.com/Dare0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/direction-arrow-6ef46718c7b242e39fcad7f27ee858a5
Title: Direction Arrow
*/

import { useGLTF } from '@react-three/drei'

export function DirectionArrow(props) {
  const { nodes, materials } = useGLTF('/models/direction_arrow.glb')
  return (
    <group scale={1} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -0.015]}>
          <group name="54b2761560d74cf7a540d3659ba46cd1fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="Arrow" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Arrow_Material001_0" geometry={nodes.Arrow_Material001_0.geometry} material-color={"purple"}  material={materials['Material.001']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/direction_arrow.glb')
