/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/low_poly_eiffel_tower.glb -o src/EifelTower.jsx -k -K -r public 
Author: Benedico2001 (https://sketchfab.com/Benedico2001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-eiffel-tower-9aef63523ee34d718522e9f012661589
Title: LOW_POLY_EIFFEL_TOWER
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function EifelTower(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_eiffel_tower.glb')

  const model = useGLTF('/models/low_poly_eiffel_tower.glb')

  //give shadows to the Eifel Tower
  model.scene.traverse((object) => {
    if(object.isMesh){
      object.castShadow = true
    }
  })
  //###
  return (
    <group {...props} dispose={null}>
       <primitive object={model.scene} />
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0_10" position={[-10.655, 1.119, 15.146]} rotation={[0, 1.273, 0]} scale={0.135}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0001_12" position={[-9.638, 1.119, 9.046]} rotation={[0, 0.502, 0]} scale={0.203}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0002_13" position={[5.61, 1.119, 10.063]} scale={0.135}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0003_14" position={[10.693, 1.119, 2.947]} rotation={[0, 0.765, 0]} scale={0.237}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0004_15" position={[13.743, 1.119, -8.235]} rotation={[0, -0.771, 0]} scale={0.135}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0005_16" position={[13.743, 1.119, -12.302]} rotation={[0, -0.139, 0]} scale={0.135}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0006_17" position={[16.793, 1.119, -12.302]} rotation={[0, 0.422, 0]} scale={0.141}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0007_18" position={[15.776, 1.119, -4.169]} rotation={[0, 1.027, 0]} scale={0.135}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0009_19" position={[-10.655, 1.119, -11.285]} rotation={[0, 0.673, 0]} scale={0.163}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0011_20" position={[-12.688, 1.119, 1.93]} rotation={[Math.PI, -1.545, Math.PI]} scale={0.135}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0013_21" position={[-12.688, 1.119, 12.096]} rotation={[0, 0.609, 0]} scale={0.135}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0014_22" position={[-7.605, 1.119, 14.129]} rotation={[0, -1.039, 0]} scale={0.135}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0015_23" position={[1.544, 1.119, 16.162]} rotation={[0, 0.215, 0]} scale={0.142}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0016_24" position={[10.693, 1.119, 16.162]} scale={0.235}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0017_25" position={[14.759, 1.119, 15.146]} scale={0.22}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0018_26" position={[11.71, 1.119, 8.03]} rotation={[0, -0.945, 0]} scale={0.163}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0019_27" position={[16.793, 1.119, -0.103]} rotation={[0, -1.149, 0]} scale={0.135}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0020_28" position={[9.677, 1.119, -4.169]} rotation={[0, -1.362, 0]} scale={0.135}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0021_29" position={[8.66, 1.119, -10.268]} rotation={[-Math.PI, -0.037, -Math.PI]} scale={0.135}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0022_30" position={[2.561, 1.119, -10.268]} rotation={[0, 0.851, 0]} scale={0.165}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0023_31" position={[-1.506, 1.119, -10.268]} scale={0.123}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0024_32" position={[-4.555, 1.119, -13.318]} rotation={[0, -0.615, 0]} scale={0.189}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0025_33" position={[-9.638, 1.119, -14.335]} scale={0.135}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0026_34" position={[-14.721, 1.119, -16.368]} rotation={[0, -0.065, 0]} scale={0.166}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0027_35" position={[-16.754, 1.119, -11.285]} rotation={[0, -0.149, 0]} scale={0.135}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0029_36" position={[14.759, 1.119, -17.384]} rotation={[Math.PI, -1.463, Math.PI]} scale={0.135}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0030_37" position={[0.528, 1.119, -14.335]} rotation={[0, -0.88, 0]} scale={0.205}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0031_38" position={[-1.506, 1.119, 14.129]} scale={0.19}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0032_39" position={[-2.522, 1.119, 11.08]} scale={0.135}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0033_40" position={[-13.704, 1.119, 18.196]} rotation={[0, -0.646, 0]} scale={0.135}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0034_41" position={[-17.567, 1.119, 12.299]} scale={0.111}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0035_42" position={[-16.551, 1.119, 0.101]} rotation={[0, 0.422, 0]} scale={0.116}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0037_43" position={[-2.319, 1.119, -16.164]} scale={0.135}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0038_44" position={[10.897, 1.119, 13.316]} rotation={[0, -1.083, 0]} scale={0.32}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="TreeBark_03_Clean_MergedBake_Bake1001_0039_45" position={[18.013, 1.119, 10.266]} scale={0.178}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials['MergedBake_Bake1.001']} />
              </group>
              <group name="Object_8001_46" position={[-14.052, 1.2, 14.067]} rotation={[0, -Math.PI / 2, 0]} scale={0.554}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_0} />
                <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.ventana} />
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials['Material.011']} />
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials['Material.012']} />
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials['Material.013']} />
                <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials['Material.014']} />
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials['Material.015']} />
                <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials['Material.016']} />
              </group>
              <group name="Object_4_51" position={[-10, 1.5, 0]} rotation={[-Math.PI, 0.302, -Math.PI]} scale={0.404}>
                <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Object_4002_52" position={[-14, 1.5, -3]} scale={0.404}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Object_4003_53" position={[-13, 1.5, -13]} rotation={[-Math.PI, -0.914, -Math.PI]} scale={0.404}>
                <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Object_4004_54" position={[-2, 1.5, -12]} rotation={[0, 0.466, 0]} scale={0.404}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Object_4005_55" position={[4, 1.5, -16]} rotation={[-Math.PI, -0.951, -Math.PI]} scale={0.404}>
                <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Object_4006_56" position={[11, 1.5, -10]} rotation={[0, 1.339, 0]} scale={0.404}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Object_4007_57" position={[15, 1.5, 2]} rotation={[0, -0.807, 0]} scale={0.404}>
                <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Object_4008_58" position={[15, 1.5, 11]} rotation={[-Math.PI, 0.429, -Math.PI]} scale={0.404}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Object_4009_59" position={[2, 1.5, 10]} rotation={[-Math.PI, 1.216, -Math.PI]} scale={0.404}>
                <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Object_4010_60" position={[9, 1.5, 10]} rotation={[-Math.PI, 1.026, -Math.PI]} scale={0.404}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.Tree_leaf} />
                <mesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.Tree_wood} />
              </group>
              <group name="Bench3_TeakWood_0_65" position={[-0.1, 1.4, 7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0_66" position={[-0.1, 1.4, 7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0001_71" position={[-0.1, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0001_72" position={[-0.1, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0002_77" position={[6.9, 1.4, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.742}>
                <mesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0002_78" position={[6.9, 1.4, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.742}>
                <mesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0003_83" position={[-7.1, 1.4, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.742}>
                <mesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0003_84" position={[-7.1, 1.4, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.742}>
                <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0004_89" position={[-16.1, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0004_90" position={[-16.1, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0005_95" position={[-14.1, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0005_96" position={[-14.1, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0006_101" position={[-14.1, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0006_102" position={[-14.1, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0007_107" position={[11.9, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0007_108" position={[11.9, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0008_113" position={[13.9, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0008_114" position={[13.9, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0009_119" position={[13.9, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0009_120" position={[13.9, 1.4, -7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0010_121" position={[-13.1, 1.4, 7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_TeakWood_0011_122" position={[-11.1, 1.4, 7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_TeakWood_0012_123" position={[14.9, 1.4, 7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_TeakWood_0013_124" position={[16.9, 1.4, 7]} rotation={[-Math.PI / 2, 0, 0]} scale={0.742}>
                <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_TeakWood_0014_125" position={[6.9, 1.4, 13]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.742}>
                <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0010_126" position={[6.9, 1.4, 13]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.742}>
                <mesh name="Object_163" geometry={nodes.Object_163.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0015_127" position={[6.9, 1.4, -11]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.742}>
                <mesh name="Object_165" geometry={nodes.Object_165.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0011_128" position={[6.9, 1.4, -11]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.742}>
                <mesh name="Object_167" geometry={nodes.Object_167.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0016_129" position={[-7.1, 1.4, -13]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.742}>
                <mesh name="Object_169" geometry={nodes.Object_169.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0012_130" position={[-7.1, 1.4, -13]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.742}>
                <mesh name="Object_171" geometry={nodes.Object_171.geometry} material={materials.MetalBase} />
              </group>
              <group name="Bench3_TeakWood_0017_131" position={[-7.1, 1.4, 12]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.742}>
                <mesh name="Object_173" geometry={nodes.Object_173.geometry} material={materials.TeakWood} />
              </group>
              <group name="Bench3_MetalBase_0013_132" position={[-7.1, 1.4, 12]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.742}>
                <mesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials.MetalBase} />
              </group>
              <group name="Sketchfab_model002_150" position={[-0.119, 0.959, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
                <group name="64cc1e09130641dcbfc8dbdc3617c047objcleanermaterialmergergle_149">
                  <group name="Object_2_133" position={[-2224.62, -3893.085, -0.001]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2001_134" position={[2224.62, -3893.085, -0.001]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_183" geometry={nodes.Object_183.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2002_135" position={[3893.086, -2224.62, 0]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_185" geometry={nodes.Object_185.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2003_136" position={[3893.086, 2224.62, 0]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2004_137" position={[-3893.086, 2224.62, 0]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_191" geometry={nodes.Object_191.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2005_138" position={[-3893.086, -2224.62, 0]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_195" geometry={nodes.Object_195.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2006_139" position={[-2224.62, 3893.085, 0]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_197" geometry={nodes.Object_197.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2007_140" position={[2224.62, 3893.085, 0]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_201" geometry={nodes.Object_201.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2009_141" position={[-8898.481, 3336.93, 0]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_203" geometry={nodes.Object_203.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2011_142" position={[8898.481, 3336.93, 0]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_207" geometry={nodes.Object_207.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2012_143" position={[9454.637, -3336.93, -0.001]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_209" geometry={nodes.Object_209.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2015_144" position={[-9454.637, -3336.93, -0.001]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2017_145" position={[-3893.086, -8898.481, -0.001]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2018_146" position={[3336.93, -8898.481, -0.001]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_219" geometry={nodes.Object_219.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2021_147" position={[3893.085, 8898.479, 0.001]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials['Material.009']} />
                  </group>
                  <group name="Object_2023_148" position={[-3336.931, 8898.479, 0.001]} rotation={[0, 0, -Math.PI / 2]}>
                    <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials['Scene_-_Root.001']} />
                    <mesh name="Object_225" geometry={nodes.Object_225.geometry} material={materials['Material.009']} />
                  </group>
                </group>
              </group>
              <group name="Sketchfab_model015_156" position={[-0.02, 0, -0.02]} rotation={[-Math.PI / 2, 0, 1.571]} scale={8.817}>
                <group name="root001_155">
                  <group name="GLTF_SceneRootNode001_154" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Plane002_1001_153">
                      <group name="Object_4001_151" position={[-1.595, 0.341, -1.643]} rotation={[0, 0, 0.419]} scale={0.111}>
                        <mesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials['Material.010']} />
                      </group>
                      <group name="Object_4011_152" position={[1.643, 0.341, 1.252]} rotation={[0, 0, 0.419]} scale={0.111}>
                        <mesh name="Object_233" geometry={nodes.Object_233.geometry} material={materials['Material.010']} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="Object_8002_157" position={[11.464, 1.2, -14.486]} rotation={[0, -Math.PI / 2, 0]} scale={0.554}>
                <mesh name="Object_235" geometry={nodes.Object_235.geometry} material={materials.colors} />
              </group>
              <group name="Cube_158" scale={[20.232, 1, 20.232]}>
                <mesh name="Object_237" geometry={nodes.Object_237.geometry} material={materials['Material.006']} />
                <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials['Material.007']} />
                <mesh name="Object_239" geometry={nodes.Object_239.geometry} material={materials['Material.008']} />
              </group>
              <group name="Cube011_159" position={[0, 1, 0]} scale={[5.542, 0.201, 5.542]}>
                <mesh name="Object_241" geometry={nodes.Object_241.geometry} material={materials['Material.002']} />
                <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials['Material.003']} />
              </group>
              <group name="Cube013_160" position={[-14.485, 2.838, 13.896]} scale={0.121}>
                <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials.material_0} />
              </group>
              <group name="Cube005_161" position={[-12, 1, 0]} scale={[5.542, 0.201, 5.542]}>
                <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials['Material.002']} />
                <mesh name="Object_247" geometry={nodes.Object_247.geometry} material={materials['Material.003']} />
              </group>
              <group name="Cube006_162" position={[12, 1, 0]} scale={[5.542, 0.201, 5.542]}>
                <mesh name="Object_249" geometry={nodes.Object_249.geometry} material={materials['Material.002']} />
                <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials['Material.003']} />
              </group>
              <group name="Cube007_163" position={[0, 1, 0]} scale={[5.542, 0.201, 5.542]}>
                <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials['Material.002']} />
                <mesh name="Object_253" geometry={nodes.Object_253.geometry} material={materials['Material.003']} />
              </group>
              <group name="Tour_Eiffel_164" position={[0, 0.8, 0]} rotation={[Math.PI / 2, 0, 0]} scale={10.276}>
                <mesh name="Object_255" geometry={nodes.Object_255.geometry} material={materials['Material.008']} />
              </group>
              <group name="Cube001_165" position={[-20.157, 0, 1.913]} scale={0.396}>
                <mesh name="Object_257" geometry={nodes.Object_257.geometry} material={materials.material_0} />
              </group>
              <group name="Cube002_166" position={[-20.027, 0, -8.143]} rotation={[-0.778, 0, 0]} scale={0.356}>
                <mesh name="Object_259" geometry={nodes.Object_259.geometry} material={materials.material_0} />
              </group>
              <group name="Cube003_167" position={[-20.157, 0, -10.094]} scale={0.356}>
                <mesh name="Object_261" geometry={nodes.Object_261.geometry} material={materials.material_0} />
              </group>
              <group name="Cube004_168" position={[-14.608, 0, -20.194]} rotation={[0, 0, 0.58]} scale={0.356}>
                <mesh name="Object_263" geometry={nodes.Object_263.geometry} material={materials.material_0} />
              </group>
              <group name="Cube008_169" position={[-2.688, 0, -20.194]} scale={0.356}>
                <mesh name="Object_265" geometry={nodes.Object_265.geometry} material={materials.material_0} />
              </group>
              <group name="Cube009_170" position={[3.706, 0, -20.055]} scale={0.356}>
                <mesh name="Object_267" geometry={nodes.Object_267.geometry} material={materials.material_0} />
              </group>
              <group name="Cube010_171" position={[12.983, 0, -20.142]} rotation={[0, 0, 1.551]} scale={0.452}>
                <mesh name="Object_269" geometry={nodes.Object_269.geometry} material={materials.material_0} />
              </group>
              <group name="Cube012_172" position={[15.8, 0, -20.055]} scale={0.356}>
                <mesh name="Object_271" geometry={nodes.Object_271.geometry} material={materials.material_0} />
              </group>
              <group name="Cube014_173" position={[20.178, 0, -16.241]} rotation={[-2.162, 0, 0]} scale={0.356}>
                <mesh name="Object_273" geometry={nodes.Object_273.geometry} material={materials.material_0} />
              </group>
              <group name="Cube015_174" position={[20.265, 0, -5.144]} rotation={[-2.251, 0, 0]} scale={0.195}>
                <mesh name="Object_275" geometry={nodes.Object_275.geometry} material={materials.material_0} />
              </group>
              <group name="Cube016_175" position={[20.135, 0, -7.528]} rotation={[-Math.PI, 0, 0]} scale={[-0.636, 0.636, 0.636]}>
                <mesh name="Object_277" geometry={nodes.Object_277.geometry} material={materials.material_0} />
              </group>
              <group name="Cube017_176" position={[20.265, 0, 7.254]} scale={0.256}>
                <mesh name="Object_279" geometry={nodes.Object_279.geometry} material={materials.material_0} />
              </group>
              <group name="Cube018_177" position={[19.787, -0.06, 16.01]} rotation={[-Math.PI, 0, 0]} scale={[-0.826, 0.826, 0.826]}>
                <mesh name="Object_281" geometry={nodes.Object_281.geometry} material={materials.material_0} />
              </group>
              <group name="Cube019_178" position={[14.977, 0, 20.128]} scale={0.356}>
                <mesh name="Object_283" geometry={nodes.Object_283.geometry} material={materials.material_0} />
              </group>
              <group name="Cube020_179" position={[5.57, 0, 19.998]} scale={0.356}>
                <mesh name="Object_285" geometry={nodes.Object_285.geometry} material={materials.material_0} />
              </group>
              <group name="Cube021_180" position={[-4.573, 0, 20.388]} scale={0.356}>
                <mesh name="Object_287" geometry={nodes.Object_287.geometry} material={materials.material_0} />
              </group>
              <group name="Cube022_181" position={[-10.598, 0, 20.085]} rotation={[0, 0, 1.224]} scale={0.209}>
                <mesh name="Object_289" geometry={nodes.Object_289.geometry} material={materials.material_0} />
              </group>
              <group name="Cube023_182" position={[-14.283, 0, 20.171]} rotation={[0, 0, -1.435]} scale={0.356}>
                <mesh name="Object_291" geometry={nodes.Object_291.geometry} material={materials.material_0} />
              </group>
              <group name="Cube024_183" position={[-20.265, 0, 17.614]} rotation={[-1.288, 0, 0]} scale={0.171}>
                <mesh name="Object_293" geometry={nodes.Object_293.geometry} material={materials.material_0} />
              </group>
              <group name="Cube025_184" position={[-20.135, 0, 16.313]} rotation={[-1.186, 0, 0]} scale={0.356}>
                <mesh name="Object_295" geometry={nodes.Object_295.geometry} material={materials.material_0} />
              </group>
              <group name="Cube026_185" position={[-3.005, -0.363, 20.388]} rotation={[0, 0, 0.878]} scale={0.157}>
                <mesh name="Object_297" geometry={nodes.Object_297.geometry} material={materials.material_0} />
              </group>
              <group name="Cube027_186" position={[-3.571, 0.319, 20.388]} rotation={[0, 0, -2.676]} scale={0.191}>
                <mesh name="Object_299" geometry={nodes.Object_299.geometry} material={materials.material_0} />
              </group>
              <group name="Cube028_187" position={[-20.265, -0.653, 16.844]} rotation={[0.745, 0, 0]} scale={0.189}>
                <mesh name="Object_301" geometry={nodes.Object_301.geometry} material={materials.material_0} />
              </group>
              <group name="Cube029_188" position={[-20.157, -0.552, -1.005]} rotation={[0.293, 0, 0]} scale={0.106}>
                <mesh name="Object_303" geometry={nodes.Object_303.geometry} material={materials.material_0} />
              </group>
              <group name="Cube030_189" position={[-20.157, -0.465, -11.444]} rotation={[1.397, 0, 0]} scale={0.199}>
                <mesh name="Object_305" geometry={nodes.Object_305.geometry} material={materials.material_0} />
              </group>
              <group name="Cube031_190" position={[-16.176, 0.392, -20.194]} rotation={[0, 0, -1.877]} scale={0.082}>
                <mesh name="Object_307" geometry={nodes.Object_307.geometry} material={materials.material_0} />
              </group>
              <group name="Cube032_191" position={[-15.987, -0.624, -20.194]} scale={0.216}>
                <mesh name="Object_309" geometry={nodes.Object_309.geometry} material={materials.material_0} />
              </group>
              <group name="Cube033_192" position={[-4.2, -0.6, -20.2]} rotation={[0, 0, -1.347]} scale={0.116}>
                <mesh name="Object_311" geometry={nodes.Object_311.geometry} material={materials.material_0} />
              </group>
              <group name="Cube034_193" position={[-4.81, -0.063, -20.2]} rotation={[0, 0, -1.347]} scale={0.13}>
                <mesh name="Object_313" geometry={nodes.Object_313.geometry} material={materials.material_0} />
              </group>
              <group name="Cube035_194" position={[20.178, -0.647, -14.678]} scale={0.149}>
                <mesh name="Object_315" geometry={nodes.Object_315.geometry} material={materials.material_0} />
              </group>
              <group name="Cube036_195" position={[20.135, -0.722, -8.444]} rotation={[-1.784, 0, 0]} scale={0.197}>
                <mesh name="Object_317" geometry={nodes.Object_317.geometry} material={materials.material_0} />
              </group>
              <group name="Cube037_196" position={[20.135, 0.05, -9.351]} scale={0.199}>
                <mesh name="Object_319" geometry={nodes.Object_319.geometry} material={materials.material_0} />
              </group>
              <group name="Cube038_197" position={[20.265, -0.648, 9.72]} scale={0.334}>
                <mesh name="Object_321" geometry={nodes.Object_321.geometry} material={materials.material_0} />
              </group>
              <group name="Cube039_198" position={[20.265, -0.648, 14.758]} scale={0.163}>
                <mesh name="Object_323" geometry={nodes.Object_323.geometry} material={materials.material_0} />
              </group>
              <group name="Cube040_199" position={[20.265, 0, 14.529]} scale={0.125}>
                <mesh name="Object_325" geometry={nodes.Object_325.geometry} material={materials.material_0} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_eiffel_tower.glb')
