/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Eiffel512.glb -o src/Eiffel512.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Eiffel512(props) {
  const { nodes, materials } = useGLTF('/models/Eiffel512.glb')
  return (
    <group scale={3} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="b64dbcc2ba974b758d6d76dd2e2bb8adfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="buildings">
                <group name="Eiffel_Tower" position={[0, 549, -163]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="_15_Mini_Eiffel_Tower001" position={[198, 49, -22]}>
                    <mesh name="_15_Mini_Eiffel_Tower001_Eiffel_Tower_0" geometry={nodes._15_Mini_Eiffel_Tower001_Eiffel_Tower_0.geometry} material={materials.Eiffel_Tower} position={[-198, -212, 8.267]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Eiffel512.glb')
