/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/london_phonebooth.glb -o src/London.jsx -k -K -r public 
Author: Wacky (https://sketchfab.com/wackyblocks)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/london-phonebooth-24204dccd16c4508bd0cc291de6980b6
Title: London Phonebooth
*/

import { useGLTF } from '@react-three/drei'

export function London(props) {
  const { nodes, materials } = useGLTF('/models/london_phonebooth.glb')
  const model = useGLTF('/models/london_phonebooth.glb')

  //give shadows to the London
  model.scene.traverse((object) => {
    if(object.isMesh){
      object.castShadow = true
    }
  })
  //###
  
  return (
    <group {...props} dispose={null}>
       <primitive object={model.scene} />
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="modelobjcleanermaterialmergergles">
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.material} />
            <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.material_1} />
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material_2} />
            <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.material_3} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/london_phonebooth.glb')
