/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/UK11.glb -o src/UK.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function UK(props) {
  const { nodes, materials } = useGLTF('/models/UK.glb')
  return (
    <group scale={100} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="071aa99bfdbb4f5994c862281f0471fcfbx" position={[-0.34, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="S_LandmarksUK_Minor_Landmarks">
                <group name="S_LandmarksS_Big_Ben">
                  <mesh name="S_LandmarksS_Big_Ben_S_LandmarksUK_0" geometry={nodes.S_LandmarksS_Big_Ben_S_LandmarksUK_0.geometry} material={materials.S_LandmarksUK} />
                </group>
                <group name="S_LandmarksS_Flagpole002">
                  <mesh name="S_LandmarksS_Flagpole_S_LandmarksUK_Flag_0" geometry={nodes.S_LandmarksS_Flagpole_S_LandmarksUK_Flag_0.geometry} material={materials.S_LandmarksUK_Flag} />
                </group>
                <group name="S_LandmarksS_Fortress_of_the_Tower_of_London">
                  <mesh name="S_LandmarksS_Fortress_of_the_Tower_of_London_S_LandmarksUK_0" geometry={nodes.S_LandmarksS_Fortress_of_the_Tower_of_London_S_LandmarksUK_0.geometry} material={materials.S_LandmarksUK} />
                </group>
                <group name="S_LandmarksS_Stonehenge">
                  <mesh name="S_LandmarksS_Stonehenge_S_LandmarksUK_0" geometry={nodes.S_LandmarksS_Stonehenge_S_LandmarksUK_0.geometry} material={materials.S_LandmarksUK} />
                </group>
                <group name="S_LandmarksS_Tower_Bridge">
                  <mesh name="S_LandmarksS_Tower_Bridge_S_LandmarksUK_0" geometry={nodes.S_LandmarksS_Tower_Bridge_S_LandmarksUK_0.geometry} material={materials.S_LandmarksUK} />
                </group>
                <group name="S_LandmarksS_Trees002">
                  <mesh name="S_LandmarksS_Trees_S_LandmarksTree_0002" geometry={nodes.S_LandmarksS_Trees_S_LandmarksTree_0002.geometry} material={materials.S_LandmarksTree} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/UK.glb')
